export const siteConfig = {
  name: "HotelPlatform",
  description: "Enterprise Hotel Booking & Owner Workflow Platform",
  links: {
    dashboard: "/owner/dashboard",
    admin: "/admin/dashboard",
    register: "/register-hotel",
  },
  categories: [
    "1 Star",
    "2 Star",
    "3 Star",
    "4 Star",
    "5 Star",
    "Boutique",
    "Guest House",
    "Apartment",
    "Resort",
    "Villa",
  ] as const,
  amenitiesList: [
    "Free Wi-Fi",
    "Swimming Pool",
    "24/7 Room Service",
    "Air Conditioning",
    "Airport Shuttle",
    "Fitness Center / Gym",
    "Spa & Wellness",
    "Free Parking",
    "Restaurant & Bar",
    "Conference Rooms",
    "Laundry Service",
    "Complimentary Breakfast",
  ] as const,
};
